/* @bruin
name: ingestion.ingest_trips_from_parquet
uri: neptune.ingestion.ingest_trips_from_parquet
type: duckdb.sql
description: |
  Reads parquet file generated by Python ingestion asset and loads into DuckDB.
  This is used with OPTION 3 (generate parquet file approach).
  The Python asset writes data to a local parquet file, and this SQL asset reads it.
  Sample query:
  ```sql
  SELECT *
  FROM ingestion.ingest_trips_from_parquet
  WHERE 1=1
  LIMIT 10
  ```

owner: data-engineering
tags:
  - ingestion
  - nyc-taxi
  - raw-data
  - parquet-reader

depends:
  - ingestion.ingest_trips_python

materialization:
  type: table
  strategy: truncate+insert

@bruin */

{#
  This asset reads from a parquet file generated by the Python ingestion asset.
  The file path should be passed as a variable or determined from the Python asset output.
  
  Note: This approach requires coordination between Python and SQL assets to manage file paths.
#}

-- Read parquet file generated by Python asset
-- File path would need to be passed via variables or determined from Python output
SELECT
  *,
FROM read_parquet('/tmp/nyc_taxi_yellow_{{ start_date }}_{{ end_date }}.parquet');

